### ISSUE TITLE
[Bug]: File unkown when deploying the app

### ISSUE THREAD

**Issue by andresj6** [marianfoo/ui5-cc-spreadsheetimporter#401]
### OData Version

OData V4

### Draft

Yes

### Scenario

Fiori Elements, List Report

### UI5 Spreadsheet Component

v0_28_1

### What happened?

When I try to deploy I get this error: 
![image](https://github.com/marianfoo/ui5-cc-spreadsheetimporter/assets/61234688/ec0ede1b-088d-4ffd-b3ae-c1619bca1d4f)
It says that the file fich.thirdparty/customControl/spreadsheetImporter/v0_28 is unknown. ¿Is it related with the version used?
Despite the error the app is deployed correctly and the component works.

I have this one in the manifest:
![image](https://github.com/marianfoo/ui5-cc-spreadsheetimporter/assets/61234688/04c9c86c-b312-4874-a750-c6643593f579)

### Relevant log output

```shell
No relevant
```

### Spreadsheet Component Init

```js
No relevant
```

### Manifest

```json
"resourceRoots": {
    "cc.spreadsheetimporter.v0_28_1": "./thirdparty/customControl/spreadsheetImporter/v0_28_1"
},
"componentUsages": {
	"spreadsheetImporter": {
		"name": "cc.spreadsheetimporter.v0_28_1"
    }
}
```

**Comment by marianfoo** [comment]
can you check if the `exclude` config in the deploy yaml helps?

```yaml
  customTasks:
  - name: deploy-to-abap
    afterTask: replaceVersion
    configuration:
      target:
        url: https://XYZ.sap-system.corp:44311
        client: 200
        auth: basic
      credentials:
        username: env:XYZ_USER
        password: env:XYZ_PASSWORD
      app:
        name: /TEST/SAMPLE_APP
        package: /TEST/UPLOAD
        transport: XYZQ300582
      exclude:
      - .*\.ts
      - *\.ts.map
```
